# Generated by Django 5.2.8 on 2025-12-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='item_image',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
