# Generated by Django 5.2.8 on 2025-12-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_fooditem_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='item_image',
            field=models.CharField(default='https://cdn-icons-png.freepik.com/256/11680/11680860.png', max_length=500),
        ),
    ]
